services:
  app:
    build:
      context: ./app
    command: gunicorn --bind 0.0.0.0:5000 --workers 1 --threads 4 main:app
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - PROFILES
    volumes:
      - ./data:/code/data
    develop:
      watch:
        - action: sync
          path: ./app
          target: /code
        - action: rebuild
          path: ./app/requirements.txt

volumes:
  neo4j_data:
